# Importing Modules

In [2]:
import pandas as pd
import numpy as np

# Data Preprocessing

## Importing Data

In [5]:
# Create a list of columns to be used for analysis

colnames = ["Year", 
            "Population", 
            "GDP",
            "Energy Consumption",
            "Energy Consumption Per Capita", 
            "Energy Intensity",
            "Energy Productivity"
           ]

# Import data from the excel file

economics = pd.read_excel("Data/australian_energy_statistics_2024_table_b.xlsx",
                          sheet_name = "AUS",
                          usecols = [1,2,3,4,5,6,7],
                          skiprows = 5,
                          skipfooter = 5,
                          names = colnames,
                         )
economics

,Year,Population,GDP,Energy Consumption,Energy Consumption Per Capita,Energy Intensity,Energy Productivity
0,1960-61,10548267,308362,1336.600,126.713,4334.516,230.706
1,1961-62,10742291,312353,1365.800,127.142,4372.617,228.696
2,1962-63,10950379,331770,1432.200,130.790,4316.846,231.651
3,1963-64,11166702,354929,1531.400,137.140,4314.666,231.768
4,1964-65,11387665,376155,1625.300,142.725,4320.825,231.437
...,...,...,...,...,...,...,...
58,2018-19,25334826,2198775,6188.282,244.260,2814.423,355.313
59,2019-20,25649248,2191416,6001.048,233.966,2738.434,365.172
60,2020-21,25685412,2237695,5769.218,224.611,2578.197,387.868
61,2021-22,26014399,2333221,5765.137,221.613,2470.892,404.712
62,2022-23,26658948,2403614,5882.206,220.647,2447.234,408.625

## Summary Statistics

In [7]:
economics.info(memory_usage = "deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Year                           63 non-null     object
 1   Population                     63 non-null     int64
 2   GDP                            63 non-null     int64
 3   Energy Consumption             63 non-null     float64
 4   Energy Consumption Per Capita  63 non-null     float64
 5   Energy Intensity               63 non-null     float64
 6   Energy Productivity            63 non-null     float64
dtypes: float64(4), int64(2), object(1)
memory usage: 6.5 KB

In [8]:
economics.describe()

,Population,GDP,Energy Consumption,Energy Consumption Per Capita,Energy Intensity,Energy Productivity
count,6.300000e+01,6.300000e+01,63.000000,63.000000,63.000000,63.000000
mean,1.775493e+07,1.123409e+06,4042.955937,219.459698,3938.108032,262.253254
std,4.548620e+06,6.227753e+05,1558.650397,41.247345,650.572407,51.923891
min,1.054827e+07,3.083620e+05,1336.600000,126.713000,2447.234000,207.437000
25%,1.411266e+07,6.030865e+05,2818.350000,198.728000,3499.379000,227.017500
50%,1.747864e+07,9.263670e+05,3982.700000,227.861000,4234.935000,236.131000
75%,2.103841e+07,1.638237e+06,5731.160500,253.057000,4404.954000,285.841500
max,2.665895e+07,2.403614e+06,6188.282000,274.827000,4820.750000,408.625000

## Converting the Fiscal Year column

In [10]:
# define a function to convert the fiscal years to calendar year

def convert_fiscal_year(x):
    x = int(x[0:4]) + 1
    return x

# apply the function to year column

economics["Year"] = economics["Year"].apply(convert_fiscal_year)

economics

,Year,Population,GDP,Energy Consumption,Energy Consumption Per Capita,Energy Intensity,Energy Productivity
0,1961,10548267,308362,1336.600,126.713,4334.516,230.706
1,1962,10742291,312353,1365.800,127.142,4372.617,228.696
2,1963,10950379,331770,1432.200,130.790,4316.846,231.651
3,1964,11166702,354929,1531.400,137.140,4314.666,231.768
4,1965,11387665,376155,1625.300,142.725,4320.825,231.437
...,...,...,...,...,...,...,...
58,2019,25334826,2198775,6188.282,244.260,2814.423,355.313
59,2020,25649248,2191416,6001.048,233.966,2738.434,365.172
60,2021,25685412,2237695,5769.218,224.611,2578.197,387.868
61,2022,26014399,2333221,5765.137,221.613,2470.892,404.712
62,2023,26658948,2403614,5882.206,220.647,2447.234,408.625

In [11]:
economics.set_index("Year", inplace = True)

In [12]:
economics

,Population,GDP,Energy Consumption,Energy Consumption Per Capita,Energy Intensity,Energy Productivity
Year,,,,,,
1961,10548267,308362,1336.600,126.713,4334.516,230.706
1962,10742291,312353,1365.800,127.142,4372.617,228.696
1963,10950379,331770,1432.200,130.790,4316.846,231.651
1964,11166702,354929,1531.400,137.140,4314.666,231.768
1965,11387665,376155,1625.300,142.725,4320.825,231.437
...,...,...,...,...,...,...
2019,25334826,2198775,6188.282,244.260,2814.423,355.313
2020,25649248,2191416,6001.048,233.966,2738.434,365.172
2021,25685412,2237695,5769.218,224.611,2578.197,387.868
2022,26014399,2333221,5765.137,221.613,2470.892,404.712
2023,26658948,2403614,5882.206,220.647,2447.234,408.625

## Creating the 1990 to 2023 Economics DataFrame

In [14]:
# Filter data to 1990 to 2023 time period

economics_1990_2023 = economics.loc[1990:2023]

economics_1990_2023

,Population,GDP,Energy Consumption,Energy Consumption Per Capita,Energy Intensity,Energy Productivity
Year,,,,,,
1990,17065128,925958,3945.900,231.226,4261.424,234.663
1991,17284036,922422,3949.900,228.529,4282.096,233.530
1992,17478635,926367,3982.700,227.861,4299.268,232.598
1993,17634808,963840,4081.800,231.463,4234.935,236.131
1994,17805468,1002198,4181.900,234.866,4172.728,239.651
1995,18004882,1041115,4365.400,242.457,4193.005,238.493
1996,18224767,1081343,4505.500,247.219,4166.578,240.005
1997,18423037,1123658,4611.100,250.290,4103.651,243.685
1998,18607584,1176057,4777.600,256.756,4062.388,246.161
1999,18812264,1235185,4884.700,259.655,3954.630,252.868
2000,19028802,1283623,4971.000,261.236,3872.632,258.222
2001,19274701,1309618,5011.800,260.020,3826.917,261.307
2002,19495210,1361736,5097.000,261.449,3743.016,267.164
2003,19720737,1403823,5138.674,260.572,3660.486,273.188
2004,19932722,1463125,5284.727,265.128,3611.945,276.859
2005,20176844,1509274,5399.200,267.594,3577.349,279.537
2006,20450966,1550859,5546.742,271.222,3576.561,279.598
2007,20827622,1609379,5723.991,274.827,3556.645,281.164
2008,21249199,1667095,5738.330,270.049,3442.113,290.519
2009,21691653,1698646,5844.233,269.423,3440.524,290.653
2010,22031750,1736467,5823.803,264.337,3353.823,298.167
2011,22340024,1778298,5902.889,264.229,3319.404,301.259
2012,22733465,1847979,5888.427,259.020,3186.414,313.832
2013,23128129,1896141,5916.732,255.824,3120.407,320.471
2014,23475686,1945581,5870.951,250.086,3017.582,331.391
2015,23815995,1988419,5898.418,247.666,2966.386,337.111
2016,24190907,2043680,6034.872,249.469,2952.944,338.645
2017,24592588,2091067,6104.651,248.231,2919.395,342.537
2018,24963258,2151841,6168.093,247.087,2866.426,348.866
2019,25334826,2198775,6188.282,244.260,2814.423,355.313
2020,25649248,2191416,6001.048,233.966,2738.434,365.172
2021,25685412,2237695,5769.218,224.611,2578.197,387.868
2022,26014399,2333221,5765.137,221.613,2470.892,404.712
2023,26658948,2403614,5882.206,220.647,2447.234,408.625

In [15]:
# Write data to a csv file 

economics_1990_2023.to_csv("data/economics_1990_2023.csv")